apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-my-app
spec:
  replicas: 3
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:latest
        ports:
        - containerPort: 80
        - containerPort: 8080

dummy commit feature03 1
dummy commit feature03 2
