apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-my-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:development
        ports:
        - containerPort: 8080